package com.hjy.entity.product;

import com.hjy.base.BaseModel;

/**
 * 商品扩展信息（要修改此类请联系作者）
 * 
 * @author ligj 2015/02/04 09:56:00
 *
 */
public class PcProductinfoExt extends BaseModel {

	private String productCodeOld;

	private String productCode;

	private String prchType;

	private String dlrId;

	private String dlrNm;

	private String oaSiteNo;

	/**
	 * 毛利润
	 *
	 * @mbggenerated
	 */
	private Long grossProfit;

	/**
	 * 积分
	 *
	 * @mbggenerated
	 */
	private Double accmRng;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.validate_flag
	 *
	 * @mbggenerated
	 */
	private String validateFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.fictitious_sales
	 *
	 * @mbggenerated
	 */
	private Integer fictitiousSales;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.poffer
	 *
	 * @mbggenerated
	 */
	private String poffer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.md_id
	 *
	 * @mbggenerated
	 */
	private String mdId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.md_nm
	 *
	 * @mbggenerated
	 */
	private String mdNm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.product_trade_type
	 *
	 * @mbggenerated
	 */
	private String productTradeType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.product_store_type
	 *
	 * @mbggenerated
	 */
	private String productStoreType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.settlement_type
	 *
	 * @mbggenerated
	 */
	private String settlementType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.purchase_type
	 *
	 * @mbggenerated
	 */
	private String purchaseType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.ld_good_id
	 *
	 * @mbggenerated
	 */
	private String ldGoodId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.pic_material_url
	 *
	 * @mbggenerated
	 */
	private String picMaterialUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.pic_material_upload
	 *
	 * @mbggenerated
	 */
	private String picMaterialUpload;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pc_productinfo_ext.kjt_seller_code
	 *
	 * @mbggenerated
	 */
	private String kjtSellerCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.product_code_old
	 *
	 * @return the value of pc_productinfo_ext.product_code_old
	 *
	 * @mbggenerated
	 */
	public String getProductCodeOld() {
		return productCodeOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.product_code_old
	 *
	 * @param productCodeOld
	 *            the value for pc_productinfo_ext.product_code_old
	 *
	 * @mbggenerated
	 */
	public void setProductCodeOld(String productCodeOld) {
		this.productCodeOld = productCodeOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.product_code
	 *
	 * @return the value of pc_productinfo_ext.product_code
	 *
	 * @mbggenerated
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.product_code
	 *
	 * @param productCode
	 *            the value for pc_productinfo_ext.product_code
	 *
	 * @mbggenerated
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.prch_type
	 *
	 * @return the value of pc_productinfo_ext.prch_type
	 *
	 * @mbggenerated
	 */
	public String getPrchType() {
		return prchType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.prch_type
	 *
	 * @param prchType
	 *            the value for pc_productinfo_ext.prch_type
	 *
	 * @mbggenerated
	 */
	public void setPrchType(String prchType) {
		this.prchType = prchType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.dlr_id
	 *
	 * @return the value of pc_productinfo_ext.dlr_id
	 *
	 * @mbggenerated
	 */
	public String getDlrId() {
		return dlrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.dlr_id
	 *
	 * @param dlrId
	 *            the value for pc_productinfo_ext.dlr_id
	 *
	 * @mbggenerated
	 */
	public void setDlrId(String dlrId) {
		this.dlrId = dlrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.dlr_nm
	 *
	 * @return the value of pc_productinfo_ext.dlr_nm
	 *
	 * @mbggenerated
	 */
	public String getDlrNm() {
		return dlrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.dlr_nm
	 *
	 * @param dlrNm
	 *            the value for pc_productinfo_ext.dlr_nm
	 *
	 * @mbggenerated
	 */
	public void setDlrNm(String dlrNm) {
		this.dlrNm = dlrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.oa_site_no
	 *
	 * @return the value of pc_productinfo_ext.oa_site_no
	 *
	 * @mbggenerated
	 */
	public String getOaSiteNo() {
		return oaSiteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.oa_site_no
	 *
	 * @param oaSiteNo
	 *            the value for pc_productinfo_ext.oa_site_no
	 *
	 * @mbggenerated
	 */
	public void setOaSiteNo(String oaSiteNo) {
		this.oaSiteNo = oaSiteNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.gross_profit
	 *
	 * @return the value of pc_productinfo_ext.gross_profit
	 *
	 * @mbggenerated
	 */
	public Long getGrossProfit() {
		return grossProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.gross_profit
	 *
	 * @param grossProfit
	 *            the value for pc_productinfo_ext.gross_profit
	 *
	 * @mbggenerated
	 */
	public void setGrossProfit(Long grossProfit) {
		this.grossProfit = grossProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.accm_rng
	 *
	 * @return the value of pc_productinfo_ext.accm_rng
	 *
	 * @mbggenerated
	 */
	public Double getAccmRng() {
		return accmRng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.accm_rng
	 *
	 * @param accmRng
	 *            the value for pc_productinfo_ext.accm_rng
	 *
	 * @mbggenerated
	 */
	public void setAccmRng(Double accmRng) {
		this.accmRng = accmRng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.validate_flag
	 *
	 * @return the value of pc_productinfo_ext.validate_flag
	 *
	 * @mbggenerated
	 */
	public String getValidateFlag() {
		return validateFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.validate_flag
	 *
	 * @param validateFlag
	 *            the value for pc_productinfo_ext.validate_flag
	 *
	 * @mbggenerated
	 */
	public void setValidateFlag(String validateFlag) {
		this.validateFlag = validateFlag;
	}

	public Integer getFictitiousSales() {
		return fictitiousSales;
	}

	public void setFictitiousSales(Integer fictitiousSales) {
		this.fictitiousSales = fictitiousSales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.poffer
	 *
	 * @return the value of pc_productinfo_ext.poffer
	 *
	 * @mbggenerated
	 */
	public String getPoffer() {
		return poffer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.poffer
	 *
	 * @param poffer
	 *            the value for pc_productinfo_ext.poffer
	 *
	 * @mbggenerated
	 */
	public void setPoffer(String poffer) {
		this.poffer = poffer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.md_id
	 *
	 * @return the value of pc_productinfo_ext.md_id
	 *
	 * @mbggenerated
	 */
	public String getMdId() {
		return mdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.md_id
	 *
	 * @param mdId
	 *            the value for pc_productinfo_ext.md_id
	 *
	 * @mbggenerated
	 */
	public void setMdId(String mdId) {
		this.mdId = mdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.md_nm
	 *
	 * @return the value of pc_productinfo_ext.md_nm
	 *
	 * @mbggenerated
	 */
	public String getMdNm() {
		return mdNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.md_nm
	 *
	 * @param mdNm
	 *            the value for pc_productinfo_ext.md_nm
	 *
	 * @mbggenerated
	 */
	public void setMdNm(String mdNm) {
		this.mdNm = mdNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.product_trade_type
	 *
	 * @return the value of pc_productinfo_ext.product_trade_type
	 *
	 * @mbggenerated
	 */
	public String getProductTradeType() {
		return productTradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.product_trade_type
	 *
	 * @param productTradeType
	 *            the value for pc_productinfo_ext.product_trade_type
	 *
	 * @mbggenerated
	 */
	public void setProductTradeType(String productTradeType) {
		this.productTradeType = productTradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.product_store_type
	 *
	 * @return the value of pc_productinfo_ext.product_store_type
	 *
	 * @mbggenerated
	 */
	public String getProductStoreType() {
		return productStoreType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.product_store_type
	 *
	 * @param productStoreType
	 *            the value for pc_productinfo_ext.product_store_type
	 *
	 * @mbggenerated
	 */
	public void setProductStoreType(String productStoreType) {
		this.productStoreType = productStoreType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.settlement_type
	 *
	 * @return the value of pc_productinfo_ext.settlement_type
	 *
	 * @mbggenerated
	 */
	public String getSettlementType() {
		return settlementType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.settlement_type
	 *
	 * @param settlementType
	 *            the value for pc_productinfo_ext.settlement_type
	 *
	 * @mbggenerated
	 */
	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	public String getPurchaseType() {
		return purchaseType;
	}

	public void setPurchaseType(String purchaseType) {
		this.purchaseType = purchaseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.ld_good_id
	 *
	 * @return the value of pc_productinfo_ext.ld_good_id
	 *
	 * @mbggenerated
	 */
	public String getLdGoodId() {
		return ldGoodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.ld_good_id
	 *
	 * @param ldGoodId
	 *            the value for pc_productinfo_ext.ld_good_id
	 *
	 * @mbggenerated
	 */
	public void setLdGoodId(String ldGoodId) {
		this.ldGoodId = ldGoodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.pic_material_url
	 *
	 * @return the value of pc_productinfo_ext.pic_material_url
	 *
	 * @mbggenerated
	 */
	public String getPicMaterialUrl() {
		return picMaterialUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.pic_material_url
	 *
	 * @param picMaterialUrl
	 *            the value for pc_productinfo_ext.pic_material_url
	 *
	 * @mbggenerated
	 */
	public void setPicMaterialUrl(String picMaterialUrl) {
		this.picMaterialUrl = picMaterialUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.pic_material_upload
	 *
	 * @return the value of pc_productinfo_ext.pic_material_upload
	 *
	 * @mbggenerated
	 */
	public String getPicMaterialUpload() {
		return picMaterialUpload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.pic_material_upload
	 *
	 * @param picMaterialUpload
	 *            the value for pc_productinfo_ext.pic_material_upload
	 *
	 * @mbggenerated
	 */
	public void setPicMaterialUpload(String picMaterialUpload) {
		this.picMaterialUpload = picMaterialUpload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pc_productinfo_ext.kjt_seller_code
	 *
	 * @return the value of pc_productinfo_ext.kjt_seller_code
	 *
	 * @mbggenerated
	 */
	public String getKjtSellerCode() {
		return kjtSellerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pc_productinfo_ext.kjt_seller_code
	 *
	 * @param kjtSellerCode
	 *            the value for pc_productinfo_ext.kjt_seller_code
	 *
	 * @mbggenerated
	 */
	public void setKjtSellerCode(String kjtSellerCode) {
		this.kjtSellerCode = kjtSellerCode;
	}
}