package com.hjy.entity.product;

import java.util.ArrayList;
import java.util.List;

public class PcProductinfoExtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public PcProductinfoExtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZidIsNull() {
            addCriterion("zid is null");
            return (Criteria) this;
        }

        public Criteria andZidIsNotNull() {
            addCriterion("zid is not null");
            return (Criteria) this;
        }

        public Criteria andZidEqualTo(Integer value) {
            addCriterion("zid =", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotEqualTo(Integer value) {
            addCriterion("zid <>", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThan(Integer value) {
            addCriterion("zid >", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidGreaterThanOrEqualTo(Integer value) {
            addCriterion("zid >=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThan(Integer value) {
            addCriterion("zid <", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidLessThanOrEqualTo(Integer value) {
            addCriterion("zid <=", value, "zid");
            return (Criteria) this;
        }

        public Criteria andZidIn(List<Integer> values) {
            addCriterion("zid in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotIn(List<Integer> values) {
            addCriterion("zid not in", values, "zid");
            return (Criteria) this;
        }

        public Criteria andZidBetween(Integer value1, Integer value2) {
            addCriterion("zid between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andZidNotBetween(Integer value1, Integer value2) {
            addCriterion("zid not between", value1, value2, "zid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldIsNull() {
            addCriterion("product_code_old is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldIsNotNull() {
            addCriterion("product_code_old is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldEqualTo(String value) {
            addCriterion("product_code_old =", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldNotEqualTo(String value) {
            addCriterion("product_code_old <>", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldGreaterThan(String value) {
            addCriterion("product_code_old >", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldGreaterThanOrEqualTo(String value) {
            addCriterion("product_code_old >=", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldLessThan(String value) {
            addCriterion("product_code_old <", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldLessThanOrEqualTo(String value) {
            addCriterion("product_code_old <=", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldLike(String value) {
            addCriterion("product_code_old like", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldNotLike(String value) {
            addCriterion("product_code_old not like", value, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldIn(List<String> values) {
            addCriterion("product_code_old in", values, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldNotIn(List<String> values) {
            addCriterion("product_code_old not in", values, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldBetween(String value1, String value2) {
            addCriterion("product_code_old between", value1, value2, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeOldNotBetween(String value1, String value2) {
            addCriterion("product_code_old not between", value1, value2, "productCodeOld");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("product_code like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("product_code not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andPrchTypeIsNull() {
            addCriterion("prch_type is null");
            return (Criteria) this;
        }

        public Criteria andPrchTypeIsNotNull() {
            addCriterion("prch_type is not null");
            return (Criteria) this;
        }

        public Criteria andPrchTypeEqualTo(String value) {
            addCriterion("prch_type =", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeNotEqualTo(String value) {
            addCriterion("prch_type <>", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeGreaterThan(String value) {
            addCriterion("prch_type >", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("prch_type >=", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeLessThan(String value) {
            addCriterion("prch_type <", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeLessThanOrEqualTo(String value) {
            addCriterion("prch_type <=", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeLike(String value) {
            addCriterion("prch_type like", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeNotLike(String value) {
            addCriterion("prch_type not like", value, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeIn(List<String> values) {
            addCriterion("prch_type in", values, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeNotIn(List<String> values) {
            addCriterion("prch_type not in", values, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeBetween(String value1, String value2) {
            addCriterion("prch_type between", value1, value2, "prchType");
            return (Criteria) this;
        }

        public Criteria andPrchTypeNotBetween(String value1, String value2) {
            addCriterion("prch_type not between", value1, value2, "prchType");
            return (Criteria) this;
        }

        public Criteria andDlrIdIsNull() {
            addCriterion("dlr_id is null");
            return (Criteria) this;
        }

        public Criteria andDlrIdIsNotNull() {
            addCriterion("dlr_id is not null");
            return (Criteria) this;
        }

        public Criteria andDlrIdEqualTo(String value) {
            addCriterion("dlr_id =", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdNotEqualTo(String value) {
            addCriterion("dlr_id <>", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdGreaterThan(String value) {
            addCriterion("dlr_id >", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdGreaterThanOrEqualTo(String value) {
            addCriterion("dlr_id >=", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdLessThan(String value) {
            addCriterion("dlr_id <", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdLessThanOrEqualTo(String value) {
            addCriterion("dlr_id <=", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdLike(String value) {
            addCriterion("dlr_id like", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdNotLike(String value) {
            addCriterion("dlr_id not like", value, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdIn(List<String> values) {
            addCriterion("dlr_id in", values, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdNotIn(List<String> values) {
            addCriterion("dlr_id not in", values, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdBetween(String value1, String value2) {
            addCriterion("dlr_id between", value1, value2, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrIdNotBetween(String value1, String value2) {
            addCriterion("dlr_id not between", value1, value2, "dlrId");
            return (Criteria) this;
        }

        public Criteria andDlrNmIsNull() {
            addCriterion("dlr_nm is null");
            return (Criteria) this;
        }

        public Criteria andDlrNmIsNotNull() {
            addCriterion("dlr_nm is not null");
            return (Criteria) this;
        }

        public Criteria andDlrNmEqualTo(String value) {
            addCriterion("dlr_nm =", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmNotEqualTo(String value) {
            addCriterion("dlr_nm <>", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmGreaterThan(String value) {
            addCriterion("dlr_nm >", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmGreaterThanOrEqualTo(String value) {
            addCriterion("dlr_nm >=", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmLessThan(String value) {
            addCriterion("dlr_nm <", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmLessThanOrEqualTo(String value) {
            addCriterion("dlr_nm <=", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmLike(String value) {
            addCriterion("dlr_nm like", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmNotLike(String value) {
            addCriterion("dlr_nm not like", value, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmIn(List<String> values) {
            addCriterion("dlr_nm in", values, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmNotIn(List<String> values) {
            addCriterion("dlr_nm not in", values, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmBetween(String value1, String value2) {
            addCriterion("dlr_nm between", value1, value2, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andDlrNmNotBetween(String value1, String value2) {
            addCriterion("dlr_nm not between", value1, value2, "dlrNm");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoIsNull() {
            addCriterion("oa_site_no is null");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoIsNotNull() {
            addCriterion("oa_site_no is not null");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoEqualTo(String value) {
            addCriterion("oa_site_no =", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoNotEqualTo(String value) {
            addCriterion("oa_site_no <>", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoGreaterThan(String value) {
            addCriterion("oa_site_no >", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoGreaterThanOrEqualTo(String value) {
            addCriterion("oa_site_no >=", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoLessThan(String value) {
            addCriterion("oa_site_no <", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoLessThanOrEqualTo(String value) {
            addCriterion("oa_site_no <=", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoLike(String value) {
            addCriterion("oa_site_no like", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoNotLike(String value) {
            addCriterion("oa_site_no not like", value, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoIn(List<String> values) {
            addCriterion("oa_site_no in", values, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoNotIn(List<String> values) {
            addCriterion("oa_site_no not in", values, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoBetween(String value1, String value2) {
            addCriterion("oa_site_no between", value1, value2, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andOaSiteNoNotBetween(String value1, String value2) {
            addCriterion("oa_site_no not between", value1, value2, "oaSiteNo");
            return (Criteria) this;
        }

        public Criteria andGrossProfitIsNull() {
            addCriterion("gross_profit is null");
            return (Criteria) this;
        }

        public Criteria andGrossProfitIsNotNull() {
            addCriterion("gross_profit is not null");
            return (Criteria) this;
        }

        public Criteria andGrossProfitEqualTo(Long value) {
            addCriterion("gross_profit =", value, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitNotEqualTo(Long value) {
            addCriterion("gross_profit <>", value, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitGreaterThan(Long value) {
            addCriterion("gross_profit >", value, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitGreaterThanOrEqualTo(Long value) {
            addCriterion("gross_profit >=", value, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitLessThan(Long value) {
            addCriterion("gross_profit <", value, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitLessThanOrEqualTo(Long value) {
            addCriterion("gross_profit <=", value, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitIn(List<Long> values) {
            addCriterion("gross_profit in", values, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitNotIn(List<Long> values) {
            addCriterion("gross_profit not in", values, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitBetween(Long value1, Long value2) {
            addCriterion("gross_profit between", value1, value2, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andGrossProfitNotBetween(Long value1, Long value2) {
            addCriterion("gross_profit not between", value1, value2, "grossProfit");
            return (Criteria) this;
        }

        public Criteria andAccmRngIsNull() {
            addCriterion("accm_rng is null");
            return (Criteria) this;
        }

        public Criteria andAccmRngIsNotNull() {
            addCriterion("accm_rng is not null");
            return (Criteria) this;
        }

        public Criteria andAccmRngEqualTo(Double value) {
            addCriterion("accm_rng =", value, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngNotEqualTo(Double value) {
            addCriterion("accm_rng <>", value, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngGreaterThan(Double value) {
            addCriterion("accm_rng >", value, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngGreaterThanOrEqualTo(Double value) {
            addCriterion("accm_rng >=", value, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngLessThan(Double value) {
            addCriterion("accm_rng <", value, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngLessThanOrEqualTo(Double value) {
            addCriterion("accm_rng <=", value, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngIn(List<Double> values) {
            addCriterion("accm_rng in", values, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngNotIn(List<Double> values) {
            addCriterion("accm_rng not in", values, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngBetween(Double value1, Double value2) {
            addCriterion("accm_rng between", value1, value2, "accmRng");
            return (Criteria) this;
        }

        public Criteria andAccmRngNotBetween(Double value1, Double value2) {
            addCriterion("accm_rng not between", value1, value2, "accmRng");
            return (Criteria) this;
        }

        public Criteria andValidateFlagIsNull() {
            addCriterion("validate_flag is null");
            return (Criteria) this;
        }

        public Criteria andValidateFlagIsNotNull() {
            addCriterion("validate_flag is not null");
            return (Criteria) this;
        }

        public Criteria andValidateFlagEqualTo(String value) {
            addCriterion("validate_flag =", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagNotEqualTo(String value) {
            addCriterion("validate_flag <>", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagGreaterThan(String value) {
            addCriterion("validate_flag >", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagGreaterThanOrEqualTo(String value) {
            addCriterion("validate_flag >=", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagLessThan(String value) {
            addCriterion("validate_flag <", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagLessThanOrEqualTo(String value) {
            addCriterion("validate_flag <=", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagLike(String value) {
            addCriterion("validate_flag like", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagNotLike(String value) {
            addCriterion("validate_flag not like", value, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagIn(List<String> values) {
            addCriterion("validate_flag in", values, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagNotIn(List<String> values) {
            addCriterion("validate_flag not in", values, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagBetween(String value1, String value2) {
            addCriterion("validate_flag between", value1, value2, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andValidateFlagNotBetween(String value1, String value2) {
            addCriterion("validate_flag not between", value1, value2, "validateFlag");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesIsNull() {
            addCriterion("fictitious_sales is null");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesIsNotNull() {
            addCriterion("fictitious_sales is not null");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesEqualTo(Integer value) {
            addCriterion("fictitious_sales =", value, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesNotEqualTo(Integer value) {
            addCriterion("fictitious_sales <>", value, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesGreaterThan(Integer value) {
            addCriterion("fictitious_sales >", value, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesGreaterThanOrEqualTo(Integer value) {
            addCriterion("fictitious_sales >=", value, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesLessThan(Integer value) {
            addCriterion("fictitious_sales <", value, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesLessThanOrEqualTo(Integer value) {
            addCriterion("fictitious_sales <=", value, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesIn(List<Integer> values) {
            addCriterion("fictitious_sales in", values, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesNotIn(List<Integer> values) {
            addCriterion("fictitious_sales not in", values, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesBetween(Integer value1, Integer value2) {
            addCriterion("fictitious_sales between", value1, value2, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andFictitiousSalesNotBetween(Integer value1, Integer value2) {
            addCriterion("fictitious_sales not between", value1, value2, "fictitiousSales");
            return (Criteria) this;
        }

        public Criteria andPofferIsNull() {
            addCriterion("poffer is null");
            return (Criteria) this;
        }

        public Criteria andPofferIsNotNull() {
            addCriterion("poffer is not null");
            return (Criteria) this;
        }

        public Criteria andPofferEqualTo(String value) {
            addCriterion("poffer =", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferNotEqualTo(String value) {
            addCriterion("poffer <>", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferGreaterThan(String value) {
            addCriterion("poffer >", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferGreaterThanOrEqualTo(String value) {
            addCriterion("poffer >=", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferLessThan(String value) {
            addCriterion("poffer <", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferLessThanOrEqualTo(String value) {
            addCriterion("poffer <=", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferLike(String value) {
            addCriterion("poffer like", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferNotLike(String value) {
            addCriterion("poffer not like", value, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferIn(List<String> values) {
            addCriterion("poffer in", values, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferNotIn(List<String> values) {
            addCriterion("poffer not in", values, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferBetween(String value1, String value2) {
            addCriterion("poffer between", value1, value2, "poffer");
            return (Criteria) this;
        }

        public Criteria andPofferNotBetween(String value1, String value2) {
            addCriterion("poffer not between", value1, value2, "poffer");
            return (Criteria) this;
        }

        public Criteria andMdIdIsNull() {
            addCriterion("md_id is null");
            return (Criteria) this;
        }

        public Criteria andMdIdIsNotNull() {
            addCriterion("md_id is not null");
            return (Criteria) this;
        }

        public Criteria andMdIdEqualTo(String value) {
            addCriterion("md_id =", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdNotEqualTo(String value) {
            addCriterion("md_id <>", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdGreaterThan(String value) {
            addCriterion("md_id >", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdGreaterThanOrEqualTo(String value) {
            addCriterion("md_id >=", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdLessThan(String value) {
            addCriterion("md_id <", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdLessThanOrEqualTo(String value) {
            addCriterion("md_id <=", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdLike(String value) {
            addCriterion("md_id like", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdNotLike(String value) {
            addCriterion("md_id not like", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdIn(List<String> values) {
            addCriterion("md_id in", values, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdNotIn(List<String> values) {
            addCriterion("md_id not in", values, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdBetween(String value1, String value2) {
            addCriterion("md_id between", value1, value2, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdNotBetween(String value1, String value2) {
            addCriterion("md_id not between", value1, value2, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdNmIsNull() {
            addCriterion("md_nm is null");
            return (Criteria) this;
        }

        public Criteria andMdNmIsNotNull() {
            addCriterion("md_nm is not null");
            return (Criteria) this;
        }

        public Criteria andMdNmEqualTo(String value) {
            addCriterion("md_nm =", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmNotEqualTo(String value) {
            addCriterion("md_nm <>", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmGreaterThan(String value) {
            addCriterion("md_nm >", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmGreaterThanOrEqualTo(String value) {
            addCriterion("md_nm >=", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmLessThan(String value) {
            addCriterion("md_nm <", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmLessThanOrEqualTo(String value) {
            addCriterion("md_nm <=", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmLike(String value) {
            addCriterion("md_nm like", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmNotLike(String value) {
            addCriterion("md_nm not like", value, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmIn(List<String> values) {
            addCriterion("md_nm in", values, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmNotIn(List<String> values) {
            addCriterion("md_nm not in", values, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmBetween(String value1, String value2) {
            addCriterion("md_nm between", value1, value2, "mdNm");
            return (Criteria) this;
        }

        public Criteria andMdNmNotBetween(String value1, String value2) {
            addCriterion("md_nm not between", value1, value2, "mdNm");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeIsNull() {
            addCriterion("product_trade_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeIsNotNull() {
            addCriterion("product_trade_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeEqualTo(String value) {
            addCriterion("product_trade_type =", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeNotEqualTo(String value) {
            addCriterion("product_trade_type <>", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeGreaterThan(String value) {
            addCriterion("product_trade_type >", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_trade_type >=", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeLessThan(String value) {
            addCriterion("product_trade_type <", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("product_trade_type <=", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeLike(String value) {
            addCriterion("product_trade_type like", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeNotLike(String value) {
            addCriterion("product_trade_type not like", value, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeIn(List<String> values) {
            addCriterion("product_trade_type in", values, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeNotIn(List<String> values) {
            addCriterion("product_trade_type not in", values, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeBetween(String value1, String value2) {
            addCriterion("product_trade_type between", value1, value2, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductTradeTypeNotBetween(String value1, String value2) {
            addCriterion("product_trade_type not between", value1, value2, "productTradeType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeIsNull() {
            addCriterion("product_store_type is null");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeIsNotNull() {
            addCriterion("product_store_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeEqualTo(String value) {
            addCriterion("product_store_type =", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeNotEqualTo(String value) {
            addCriterion("product_store_type <>", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeGreaterThan(String value) {
            addCriterion("product_store_type >", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_store_type >=", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeLessThan(String value) {
            addCriterion("product_store_type <", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeLessThanOrEqualTo(String value) {
            addCriterion("product_store_type <=", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeLike(String value) {
            addCriterion("product_store_type like", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeNotLike(String value) {
            addCriterion("product_store_type not like", value, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeIn(List<String> values) {
            addCriterion("product_store_type in", values, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeNotIn(List<String> values) {
            addCriterion("product_store_type not in", values, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeBetween(String value1, String value2) {
            addCriterion("product_store_type between", value1, value2, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andProductStoreTypeNotBetween(String value1, String value2) {
            addCriterion("product_store_type not between", value1, value2, "productStoreType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeIsNull() {
            addCriterion("settlement_type is null");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeIsNotNull() {
            addCriterion("settlement_type is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeEqualTo(String value) {
            addCriterion("settlement_type =", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotEqualTo(String value) {
            addCriterion("settlement_type <>", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeGreaterThan(String value) {
            addCriterion("settlement_type >", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeGreaterThanOrEqualTo(String value) {
            addCriterion("settlement_type >=", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeLessThan(String value) {
            addCriterion("settlement_type <", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeLessThanOrEqualTo(String value) {
            addCriterion("settlement_type <=", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeLike(String value) {
            addCriterion("settlement_type like", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotLike(String value) {
            addCriterion("settlement_type not like", value, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeIn(List<String> values) {
            addCriterion("settlement_type in", values, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotIn(List<String> values) {
            addCriterion("settlement_type not in", values, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeBetween(String value1, String value2) {
            addCriterion("settlement_type between", value1, value2, "settlementType");
            return (Criteria) this;
        }

        public Criteria andSettlementTypeNotBetween(String value1, String value2) {
            addCriterion("settlement_type not between", value1, value2, "settlementType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeIsNull() {
            addCriterion("purchase_type is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeIsNotNull() {
            addCriterion("purchase_type is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeEqualTo(String value) {
            addCriterion("purchase_type =", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeNotEqualTo(String value) {
            addCriterion("purchase_type <>", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeGreaterThan(String value) {
            addCriterion("purchase_type >", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("purchase_type >=", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeLessThan(String value) {
            addCriterion("purchase_type <", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeLessThanOrEqualTo(String value) {
            addCriterion("purchase_type <=", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeLike(String value) {
            addCriterion("purchase_type like", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeNotLike(String value) {
            addCriterion("purchase_type not like", value, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeIn(List<String> values) {
            addCriterion("purchase_type in", values, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeNotIn(List<String> values) {
            addCriterion("purchase_type not in", values, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeBetween(String value1, String value2) {
            addCriterion("purchase_type between", value1, value2, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andPurchaseTypeNotBetween(String value1, String value2) {
            addCriterion("purchase_type not between", value1, value2, "purchaseType");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdIsNull() {
            addCriterion("ld_good_id is null");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdIsNotNull() {
            addCriterion("ld_good_id is not null");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdEqualTo(String value) {
            addCriterion("ld_good_id =", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdNotEqualTo(String value) {
            addCriterion("ld_good_id <>", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdGreaterThan(String value) {
            addCriterion("ld_good_id >", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdGreaterThanOrEqualTo(String value) {
            addCriterion("ld_good_id >=", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdLessThan(String value) {
            addCriterion("ld_good_id <", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdLessThanOrEqualTo(String value) {
            addCriterion("ld_good_id <=", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdLike(String value) {
            addCriterion("ld_good_id like", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdNotLike(String value) {
            addCriterion("ld_good_id not like", value, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdIn(List<String> values) {
            addCriterion("ld_good_id in", values, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdNotIn(List<String> values) {
            addCriterion("ld_good_id not in", values, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdBetween(String value1, String value2) {
            addCriterion("ld_good_id between", value1, value2, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andLdGoodIdNotBetween(String value1, String value2) {
            addCriterion("ld_good_id not between", value1, value2, "ldGoodId");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlIsNull() {
            addCriterion("pic_material_url is null");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlIsNotNull() {
            addCriterion("pic_material_url is not null");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlEqualTo(String value) {
            addCriterion("pic_material_url =", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlNotEqualTo(String value) {
            addCriterion("pic_material_url <>", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlGreaterThan(String value) {
            addCriterion("pic_material_url >", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pic_material_url >=", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlLessThan(String value) {
            addCriterion("pic_material_url <", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlLessThanOrEqualTo(String value) {
            addCriterion("pic_material_url <=", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlLike(String value) {
            addCriterion("pic_material_url like", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlNotLike(String value) {
            addCriterion("pic_material_url not like", value, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlIn(List<String> values) {
            addCriterion("pic_material_url in", values, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlNotIn(List<String> values) {
            addCriterion("pic_material_url not in", values, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlBetween(String value1, String value2) {
            addCriterion("pic_material_url between", value1, value2, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUrlNotBetween(String value1, String value2) {
            addCriterion("pic_material_url not between", value1, value2, "picMaterialUrl");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadIsNull() {
            addCriterion("pic_material_upload is null");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadIsNotNull() {
            addCriterion("pic_material_upload is not null");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadEqualTo(String value) {
            addCriterion("pic_material_upload =", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadNotEqualTo(String value) {
            addCriterion("pic_material_upload <>", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadGreaterThan(String value) {
            addCriterion("pic_material_upload >", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadGreaterThanOrEqualTo(String value) {
            addCriterion("pic_material_upload >=", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadLessThan(String value) {
            addCriterion("pic_material_upload <", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadLessThanOrEqualTo(String value) {
            addCriterion("pic_material_upload <=", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadLike(String value) {
            addCriterion("pic_material_upload like", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadNotLike(String value) {
            addCriterion("pic_material_upload not like", value, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadIn(List<String> values) {
            addCriterion("pic_material_upload in", values, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadNotIn(List<String> values) {
            addCriterion("pic_material_upload not in", values, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadBetween(String value1, String value2) {
            addCriterion("pic_material_upload between", value1, value2, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andPicMaterialUploadNotBetween(String value1, String value2) {
            addCriterion("pic_material_upload not between", value1, value2, "picMaterialUpload");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeIsNull() {
            addCriterion("kjt_seller_code is null");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeIsNotNull() {
            addCriterion("kjt_seller_code is not null");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeEqualTo(String value) {
            addCriterion("kjt_seller_code =", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeNotEqualTo(String value) {
            addCriterion("kjt_seller_code <>", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeGreaterThan(String value) {
            addCriterion("kjt_seller_code >", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("kjt_seller_code >=", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeLessThan(String value) {
            addCriterion("kjt_seller_code <", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeLessThanOrEqualTo(String value) {
            addCriterion("kjt_seller_code <=", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeLike(String value) {
            addCriterion("kjt_seller_code like", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeNotLike(String value) {
            addCriterion("kjt_seller_code not like", value, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeIn(List<String> values) {
            addCriterion("kjt_seller_code in", values, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeNotIn(List<String> values) {
            addCriterion("kjt_seller_code not in", values, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeBetween(String value1, String value2) {
            addCriterion("kjt_seller_code between", value1, value2, "kjtSellerCode");
            return (Criteria) this;
        }

        public Criteria andKjtSellerCodeNotBetween(String value1, String value2) {
            addCriterion("kjt_seller_code not between", value1, value2, "kjtSellerCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pc_productinfo_ext
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}