package com.hjy.entity.system;

/**
 * 
 * 类: ScStoreSkunum <br>
 * 描述: 库存表 <br>
 * 作者: 张海宇 zhanghaiyu@huijiayou.cn<br>
 * 时间: 2016年6月28日 下午2:44:26
 */
public class ScStoreSkunum {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc_store_skunum.zid
	 *
	 * @mbggenerated
	 */
	private Integer zid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc_store_skunum.uid
	 *
	 * @mbggenerated
	 */
	private String uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc_store_skunum.store_code
	 *
	 * @mbggenerated
	 */
	private String storeCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc_store_skunum.sku_code
	 *
	 * @mbggenerated
	 */
	private String skuCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc_store_skunum.batch_code
	 *
	 * @mbggenerated
	 */
	private String batchCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc_store_skunum.stock_num
	 *
	 * @mbggenerated
	 */
	private Long stockNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc_store_skunum.zid
	 *
	 * @return the value of sc_store_skunum.zid
	 *
	 * @mbggenerated
	 */
	public Integer getZid() {
		return zid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc_store_skunum.zid
	 *
	 * @param zid
	 *            the value for sc_store_skunum.zid
	 *
	 * @mbggenerated
	 */
	public void setZid(Integer zid) {
		this.zid = zid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc_store_skunum.uid
	 *
	 * @return the value of sc_store_skunum.uid
	 *
	 * @mbggenerated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc_store_skunum.uid
	 *
	 * @param uid
	 *            the value for sc_store_skunum.uid
	 *
	 * @mbggenerated
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc_store_skunum.store_code
	 *
	 * @return the value of sc_store_skunum.store_code
	 *
	 * @mbggenerated
	 */
	public String getStoreCode() {
		return storeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc_store_skunum.store_code
	 *
	 * @param storeCode
	 *            the value for sc_store_skunum.store_code
	 *
	 * @mbggenerated
	 */
	public void setStoreCode(String storeCode) {
		this.storeCode = storeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc_store_skunum.sku_code
	 *
	 * @return the value of sc_store_skunum.sku_code
	 *
	 * @mbggenerated
	 */
	public String getSkuCode() {
		return skuCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc_store_skunum.sku_code
	 *
	 * @param skuCode
	 *            the value for sc_store_skunum.sku_code
	 *
	 * @mbggenerated
	 */
	public void setSkuCode(String skuCode) {
		this.skuCode = skuCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc_store_skunum.batch_code
	 *
	 * @return the value of sc_store_skunum.batch_code
	 *
	 * @mbggenerated
	 */
	public String getBatchCode() {
		return batchCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc_store_skunum.batch_code
	 *
	 * @param batchCode
	 *            the value for sc_store_skunum.batch_code
	 *
	 * @mbggenerated
	 */
	public void setBatchCode(String batchCode) {
		this.batchCode = batchCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc_store_skunum.stock_num
	 *
	 * @return the value of sc_store_skunum.stock_num
	 *
	 * @mbggenerated
	 */
	public Long getStockNum() {
		return stockNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc_store_skunum.stock_num
	 *
	 * @param stockNum
	 *            the value for sc_store_skunum.stock_num
	 *
	 * @mbggenerated
	 */
	public void setStockNum(Long stockNum) {
		this.stockNum = stockNum;
	}
}