package com.hjy.entity.log;

import java.util.Date;

public class LcStockchange {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.zid
	 * @mbggenerated
	 */
	private Integer zid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.uid
	 * @mbggenerated
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.code
	 * @mbggenerated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.info
	 * @mbggenerated
	 */
	private String info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.create_time
	 * @mbggenerated
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.create_user
	 * @mbggenerated
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.change_stock
	 * @mbggenerated
	 */
	private Integer changeStock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.old_stock
	 * @mbggenerated
	 */
	private Integer oldStock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.now_stock
	 * @mbggenerated
	 */
	private Integer nowStock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.change_type
	 * @mbggenerated
	 */
	private String changeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.stock_area
	 * @mbggenerated
	 */
	private String stockArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lc_stockchange.stock_batch
	 * @mbggenerated
	 */
	private String stockBatch;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.zid
	 * @return  the value of lc_stockchange.zid
	 * @mbggenerated
	 */
	public Integer getZid() {
		return zid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.zid
	 * @param zid  the value for lc_stockchange.zid
	 * @mbggenerated
	 */
	public void setZid(Integer zid) {
		this.zid = zid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.uid
	 * @return  the value of lc_stockchange.uid
	 * @mbggenerated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.uid
	 * @param uid  the value for lc_stockchange.uid
	 * @mbggenerated
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.code
	 * @return  the value of lc_stockchange.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.code
	 * @param code  the value for lc_stockchange.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.info
	 * @return  the value of lc_stockchange.info
	 * @mbggenerated
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.info
	 * @param info  the value for lc_stockchange.info
	 * @mbggenerated
	 */
	public void setInfo(String info) {
		this.info = info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.create_time
	 * @return  the value of lc_stockchange.create_time
	 * @mbggenerated
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.create_time
	 * @param createTime  the value for lc_stockchange.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.create_user
	 * @return  the value of lc_stockchange.create_user
	 * @mbggenerated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.create_user
	 * @param createUser  the value for lc_stockchange.create_user
	 * @mbggenerated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.change_stock
	 * @return  the value of lc_stockchange.change_stock
	 * @mbggenerated
	 */
	public Integer getChangeStock() {
		return changeStock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.change_stock
	 * @param changeStock  the value for lc_stockchange.change_stock
	 * @mbggenerated
	 */
	public void setChangeStock(Integer changeStock) {
		this.changeStock = changeStock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.old_stock
	 * @return  the value of lc_stockchange.old_stock
	 * @mbggenerated
	 */
	public Integer getOldStock() {
		return oldStock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.old_stock
	 * @param oldStock  the value for lc_stockchange.old_stock
	 * @mbggenerated
	 */
	public void setOldStock(Integer oldStock) {
		this.oldStock = oldStock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.now_stock
	 * @return  the value of lc_stockchange.now_stock
	 * @mbggenerated
	 */
	public Integer getNowStock() {
		return nowStock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.now_stock
	 * @param nowStock  the value for lc_stockchange.now_stock
	 * @mbggenerated
	 */
	public void setNowStock(Integer nowStock) {
		this.nowStock = nowStock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.change_type
	 * @return  the value of lc_stockchange.change_type
	 * @mbggenerated
	 */
	public String getChangeType() {
		return changeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.change_type
	 * @param changeType  the value for lc_stockchange.change_type
	 * @mbggenerated
	 */
	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.stock_area
	 * @return  the value of lc_stockchange.stock_area
	 * @mbggenerated
	 */
	public String getStockArea() {
		return stockArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.stock_area
	 * @param stockArea  the value for lc_stockchange.stock_area
	 * @mbggenerated
	 */
	public void setStockArea(String stockArea) {
		this.stockArea = stockArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lc_stockchange.stock_batch
	 * @return  the value of lc_stockchange.stock_batch
	 * @mbggenerated
	 */
	public String getStockBatch() {
		return stockBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lc_stockchange.stock_batch
	 * @param stockBatch  the value for lc_stockchange.stock_batch
	 * @mbggenerated
	 */
	public void setStockBatch(String stockBatch) {
		this.stockBatch = stockBatch;
	}
}